version: 2.1

jobs:
  run_npm_start:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm start

  run_regression_tests:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run regression

workflows:
  version: 2
  start_and_regression:
    jobs:
      - run_npm_start
      - run_regression_tests
